blueprint:
  name: Oil Diffuser Ai
  description: |
    ![OilDiffuser](https://raw.githubusercontent.com/zodyking/oil-diffuser-blueprint/refs/heads/main/ChatGPT%20Image%20Oct%2018%2C%202025%2C%2007_21_16%20PM.png)

    Control a waterless oil diffuser via a smart outlet with **two independent modes** that can run at the same time:
    • Duty cycle — every X minutes, turn ON for Y minutes  
    • Presence — when presence is detected, turn ON for Z minutes  
    Optional TTS before ON and a safety max-runtime cutoff.
  domain: automation
  author: chat.openai.com/@gpt
  source_url: https://example.com/blueprints/oil_diffuser_ai

  input:
    # ---- Core entities (grouped together) ----
    outlet_switch:
      name: Diffuser outlet
      description: "Select the smart outlet that powers the diffuser."
      selector:
        entity:
          domain: switch

    presence_sensor:
      name: Presence / motion sensor
      description: "Binary sensor used for Presence mode (leave empty to disable Presence mode)."
      default: ""
      selector:
        entity:
          domain: binary_sensor

    # ---- Mode toggles (grouped together) ----
    duty_enabled:
      name: Duty cycle enabled
      description: "Runs a periodic cycle: every X minutes, turn ON for Y duration."
      default: true
      selector:
        boolean: {}

    presence_enabled:
      name: Presence mode enabled
      description: "Turns ON when the presence sensor changes to the selected state, then runs for Z duration."
      default: true
      selector:
        boolean: {}

    # ---- Duty cycle settings ----
    duty_interval_minutes:
      name: Duty cycle interval (minutes)
      description: "Every X minutes, start one ON period."
      default: 30
      selector:
        number:
          min: 1
          max: 1440
          step: 1
          unit_of_measurement: min

    duty_on_duration:
      name: Duty cycle ON duration
      description: "How long to keep the outlet ON each cycle."
      default:
        hours: 0
        minutes: 8
        seconds: 0
      selector:
        duration: {}

    # ---- Presence settings ----
    presence_on_state:
      name: Presence 'ON' state
      description: "Which state means detected/present for your sensor."
      default: "on"
      selector:
        select:
          options: ["on", "home", "occupied", "detected"]

    presence_on_duration:
      name: Presence ON duration
      description: "How long to keep the outlet ON after presence is detected."
      default:
        hours: 0
        minutes: 20
        se
